 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  conceptual_caption_3m_hdfs:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: hdfs://haruna/home/byte_uslab_cvg/user/linjieyang/blip2/conceptualCap/train_filtered.pkl 
      images:
          storage: hdfs://haruna/home/byte_uslab_cvg/user/linjieyang/blip2/conceptualCap/train_filtered
