 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: pretrain_video_cascade_opt2.7b
  load_finetuned: False

  pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_opt2.7b.pth"
  finetuned: ""

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32
  # Q-Former for video
  num_query_token_v: 32
  # OPT
  opt_model: "facebook/opt-2.7b"
  video_qformer_layers: 1
  # generation configs
  prompt: ""


preprocess:
    vis_processor:
        train:
          name: "blip_video_train"
          n_frms: 8
          image_size: 224
        eval:
          name: "blip_video_eval"
          n_frms: 8
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
