model:
  arch: mini_gpt4

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True
  freeze_qformer: True

  # Q-Former
  num_query_token: 32

  # Vicuna
  llama_model: "/opt/tiger/vicuna_13B"

  # generation configs
  prompt: ""

preprocess:
    vis_processor:
        train:
          name: "blip2_video_train"
          n_frms: 1
          image_size: 224
        eval:
          name: "blip_video_eval"
          n_frms: 1
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
